# Feature Scaling 

In [1]:
import numpy as np
import pandas as pd
from sklearn import preprocessing
import matplotlib.pyplot as plt
%matplotlib inline

In [4]:
data=pd.read_csv('Data_for_Missing_Values.csv')
data.head(15)

Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes
5   France  35.0  58000.0       Yes
6    Spain   NaN  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes

As we can see that we have some missing values, we will drop them.

In [20]:
data=data.dropna()
data

Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
5   France  35.0  58000.0       Yes
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes

In [13]:
#calculationg mean,median before feature scaling
data.mean()

Age          38.625
Salary    65250.000
dtype: float64

In [14]:
data.median()

Age          37.5
Salary    64000.0
dtype: float64

We can clearly observe features Age and Salary have values of varying magnitude. This is where feature scaling can help us resolve this issue.

In [19]:
#slicing the feature age and salary
df=data.iloc[:,1:3].values
df

array([[4.4e+01, 7.2e+04],
       [2.7e+01, 4.8e+04],
       [3.0e+01, 5.4e+04],
       [3.8e+01, 6.1e+04],
       [3.5e+01, 5.8e+04],
       [4.8e+01, 7.9e+04],
       [5.0e+01, 8.3e+04],
       [3.7e+01, 6.7e+04]])

In [23]:
#MinMaxScaler or Normalization
min_max_scaler=preprocessing.MinMaxScaler(feature_range=(0,1))
df_after_minmax=min_max_scaler.fit_transform(df)
df_after_minmax

array([[0.73913043, 0.68571429],
       [0.        , 0.        ],
       [0.13043478, 0.17142857],
       [0.47826087, 0.37142857],
       [0.34782609, 0.28571429],
       [0.91304348, 0.88571429],
       [1.        , 1.        ],
       [0.43478261, 0.54285714]])

In [29]:
#Standarization
ss=preprocessing.StandardScaler()
df_after_ss=ss.fit_transform(df)
df_after_ss

array([[ 0.69985807,  0.58989097],
       [-1.51364653, -1.50749915],
       [-1.12302807, -0.98315162],
       [-0.08137885, -0.37141284],
       [-0.47199731, -0.6335866 ],
       [ 1.22068269,  1.20162976],
       [ 1.48109499,  1.55119478],
       [-0.211585  ,  0.1529347 ]])

In [25]:
#calculating mean,median after feature scaling
df_after_minmax.mean()

0.4991459627329192

In [27]:
df_after_ss.mean()

5.551115123125783e-17